[workspace]

members = [
  "crates/adapters/*",
  "crates/components/*",
  "crates/plugins/*",
  "crates/apps/*",
  "crates/systems/*",
  "crates/libs/*",
  "crates/tests/*",
]

default-members = [
  "crates/adapters/*",
  "crates/components/*",
  "crates/plugins/*",
  "crates/apps/*",
  "crates/systems/*",
]

[profile.dev]
# Disable for build speed
debug = 0
