[package]
name = "desk-shell-language"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
language = { package = "desk-language", path = "../../components/language", version = "0.1.0" }
physics = { package = "desk-physics", path = "../../components/physics", version = "0.1.0" }

bevy_math = "0.5.0"