[package]
name = "desk-client"
version = "0.1.0"
authors = ["Ryo Hirayama <ryo12redstone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { package = "desk-plugin-core", path = "../../plugins/core" }
physics-heron = { package = "desk-plugin-physics-heron", path = "../../plugins/physics-heron" }
egui = { package = "desk-plugin-egui", path = "../../plugins/egui" }

bevy = "0.5"