[package]
name = "desk-shell-terminal"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal = { package = "desk-terminal", path = "../../components/terminal", version = "0.1.0" }
physics = { package = "desk-physics", path = "../../components/physics", version = "0.1.0" }