name: CI
on:
  push:
    branches:
      - main
env:
  IMAGE: gcr.io/hihaheho/desk-server
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -W rust-2021-compatibility"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install --no-install-recommends libasound2-dev -y
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          components: rustfmt, clippy
      - run: rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v1

      - name: Check
        run: cargo check --workspace

      - name: Check native
        run: cargo check -p desk-client --features native

      - name: Compile test
        run: cargo test --no-run --locked --all-features

      - name: Run test
        run: cargo test --all-features

      - name: Check fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings -W clippy::all -W clippy::dbg_macro

      - name: Deny
        run: cargo deny --all-features check

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .deploy/desk-server/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ env.IMAGE }}:${{ github.sha }}
      - run: docker tag ${{ env.IMAGE }}:${{ github.sha }} ${{ env.IMAGE }}:latest

      - name: Compile E2E
        run: cargo test -p desk-test-server --no-run --locked

      - name: Run E2E
        run: cargo test -p desk-test-server

      - run: cargo install wasm-bindgen-cli --version 0.2.69

      - name: Build wasm
        run: cargo build --bin desk-client --target wasm32-unknown-unknown --release --features web

      - name: wasm-bindgen
        run: wasm-bindgen --out-dir .public --target web target/wasm32-unknown-unknown/release/desk-client.wasm

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .public

      - name: Deploy to production
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: desk-server
          image: ${{ env.IMAGE }}:${{ github.sha }}
          region: us-west1
