name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true
          components: rustfmt, clippy

      - run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev -y
      - run: cargo install cargo-make
      - run: rustup target add wasm32-unknown-unknown

      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: make
          args: ci-check

      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: make
          args: wasm-bindgen

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          log-level: warn
          command: check
          arguments: --all-features
