name: Deploy
on: workflow_dispatch
env:
  IMAGE: gcr.io/hihaheho/desk-system
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - run: DOCKER_BUILDKIT=1 docker build . -f .deploy/desk-server/Dockerfile -t gcr.io/hihaheho/desk-system:latest

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - run: gcloud auth configure-docker

      - run:
          docker pull ${{ env.IMAGE }}:latest
          docker tag ${{ env.IMAGE }}:latest ${{ env.IMAGE }}:${{ github.sha }}
          docker push ${{ env.IMAGE }}:${{ github.sha }}

      - name: Deploy to production
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: desk-server
          image: ${{ env.IMAGE }}:${{ github.sha }}
          region: us-west1
