name: Deploy
on: workflow_dispatch
env:
  IMAGE: gcr.io/hihaheho/desk-system
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - run: gcloud auth configure-docker

      - run: DOCKER_BUILDKIT=1 docker build . -f .deploy/desk-server/Dockerfile -t ${{ env.IMAGE }}:${{ github.sha }}

      - run: docker push ${{ env.IMAGE }}:${{ github.sha }}

      - name: Deploy to production
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: desk-server
          image: ${{ env.IMAGE }}:${{ github.sha }}
          region: us-west1
