name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true

      - run: cargo install cargo-make
      - run: rustup target add wasm32-unknown-unknown

      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: make
          args: wasm-bindgen

      - run: ls -a
      - run: ls -a target
      - run: ls -a target/wasm32-unknown-unknown
      - run: ls -a target/wasm32-unknown-unknown/release
      - run: ls -a target/release

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
