name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true
      - uses: Swatinem/rust-cache@v1

      - run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev -y
      - run: cargo install cargo-make
      - run: cargo install wasm-bindgen-cli --version 0.2.69
      - run: rustup target add wasm32-unknown-unknown

      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: make
          args: wasm-bindgen

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .public
